PcrdWiki/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.i18n import i18n_patterns

from pcrd_unpack.sitemaps import UnitSitemap, EquimpmentSitemap

sitemaps = {
    'unit': UnitSitemap,
    'equipment': EquimpmentSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
]

urlpatterns += i18n_patterns(
    path("", include("pcrd_unpack.urls")),
)

handler404 = 'pcrd_unpack.views.handler404'

pcrd_unpack/urls.py
from django.contrib import admin
from django.urls import path
import django.contrib.auth.views
from datetime import datetime
import pcrd_unpack.forms
from . import views


app_name = 'pcrd_unpack'

urlpatterns  = [
    path("", views.IndexView.as_view(), name="index"),
    path("unit_data/<int:unit_id>", views.UnitJsonView.as_view(), name="unit_json"),
    path("unit/<int:unit_id>", views.UnitDetailView.as_view(), name="unit"),
    path("unit/", views.UnitListView.as_view(), name="unit_list"),
    path("summary/", views.UnitSummaryView.as_view(), name="unit_summary"),
    path("item/<int:item_id>", views.ItemView.as_view(), name="item"),
    path("equipment_list/", views.EquipmentListView.as_view(), name="equipment_list"),
    path("area/", views.QuestAreaListView.as_view(), name="area"),
    path("area/<int:area_id>", views.QuestAreaDetailView.as_view(), name="area_detail"),
    path("equipment/<int:equipment_id>", views.EquipmentView.as_view(), name="equipment"),
    path("solution/create", views.CreateSolutionView.as_view(),name="create_solution"),
    path("solution/add", views.create_solution_handler, name="add_solution"),
    path("solution/search", views.SolutionSearchView.as_view(), name="search_solution"),
    path("solution/view/<str:solution_id>", views.SolutionView.as_view(), name="solution"),
    path("solution", views.SolutionIndexView.as_view(), name="solution_index"),
    path("enemy_list", views.EnemyListView.as_view(), name="enemy_list"),
    path("vote", views.vote, name="vote"),
    # path("404", views.handler404),
    path('login/',
         django.contrib.auth.views.login,
         {
             'template_name': 'pcrd_unpack/login.html',
             'authentication_form': pcrd_unpack.forms.BootstrapAuthenticationForm,
             'extra_context':
                 {
                     'title': 'Log in',
                     'year': datetime.now().year,
                 }
         },
         name='login'),
    path('logout',
         django.contrib.auth.views.logout,
         {
             'next_page': '/',
         },
         name='logout'),
]

pcrd_unpack/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse
from . import coop
# Create your views here.
from . import models

class EquipmentView(TemplateView):
    """docstring for """
    template_name = "pcrd_unpack/equipment.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        eq = get_object_or_404(models.EquipmentData, pk=self.kwargs["equipment_id"])
        context['equipment'] = eq
        drops = eq.questrewarddatacustom_set.all()
        quests = [i.quest for i in drops]
        context['drop_info'] = dict(zip(quests, [q.questrewarddatacustom_set.order_by('-rate') for q in quests]))
        if eq.craft_flg:
            cinfo =  get_object_or_404(models.EquipmentCraft, pk=self.kwargs["equipment_id"])
            context["craft_info"] = cinfo
            components = {}
            for i in range(1, 11):
                eqid = getattr(cinfo, "condition_equipment_id_{}".format(i))
                eq_num = getattr(cinfo, "consume_num_{}".format(i))
                if eqid:
                    components[eqid] = eq_num
            context["components"] = components
        return context

class EquipmentListView(ListView):
    """docstring for Equi"""
    template_name = "pcrd_unpack/equipment_list.html"
    # model = models.EquipmentData

    def get_queryset(self):
        return models.EquipmentData.objects.order_by("-promotion_level")

class ItemView(TemplateView):
    """docstring for """
    template_name = "pcrd_unpack/item.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = get_object_or_404(models.ItemData, pk=self.kwargs["item_id"])
        context['item'] = item
        drops = item.questrewarddatacustom_set.all()
        quests = [i.quest for i in drops]
        context['drop_info'] = dict(zip(quests, [q.questrewarddatacustom_set.order_by('-rate') for q in quests]))
        return context

# class ItemListView(ListView):
#     """docstring for Equi"""
#     template_name = "pcrd_unpack/item_list.html"
#     # model = models.EquipmentData
#
#     def get_queryset(self):
#         return models.ItemData.objects.order_by("-promotion_level")


class QuestAreaListView(ListView):
    """docstring for QuestAreaListView"""
    template_name = "pcrd_unpack/quests_list.html"
    model = models.QuestAreaData

class QuestAreaDetailView(TemplateView):
    """docstring for QuestAreaDetailView"""
    template_name = "pcrd_unpack/quest_area_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        area_id = self.kwargs["area_id"]
        area = get_object_or_404(models.QuestAreaData.objects, pk=area_id)
        context["area_title"] = area.area_name
        quests_in_charpter = models.QuestData.objects.filter(area_id=area_id)
        context["quests_in_charpter"] = quests_in_charpter
        context["quest_reward"] = {}
        for q in quests_in_charpter:
            context["quest_reward"][q] = q.questrewarddatacustom_set.order_by('-rate')
        return context

class UnitListView(ListView):
    """docstring for UnitListView"""
    template_name = "pcrd_unpack/unit_list.html"
    model = models.UnitData

    def get_queryset(self, **hints):
        return self.model.objects.exclude(comment__isnull=True).order_by("-rarity")



class UnitDetailView(TemplateView):
    """docstring for UnitDetailView"""
    template_name = "pcrd_unpack/unit_detail.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        unit_id = kwargs["unit_id"]
        unit_data = get_object_or_404(models.UnitData, pk=unit_id)
        unit_data.comment = unit_data.comment.replace("\\n", "\n")
        unit_profile = get_object_or_404(models.UnitProfile, pk=unit_id)
        unit_promotion = get_list_or_404(models.UnitPromotion, pk=unit_id)
        context["unit_data"] = unit_data
        context["unit_profile"] = unit_profile
        context["unit_promotion"] = unit_promotion
        return context




def handler404(request, exception):
    return render(request, 'pcrd_unpack/errors/404.html', locals())

pcrd_unpack/views/enemy_view.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from itertools import zip_longest
from django.http import HttpResponseNotFound
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from collections import OrderedDict
from pcrd_unpack.utils import skill_utility


class EnemyListView(TemplateView):
    """docstring for EnemyListView"""
    template_name = "pcrd_unpack/enemy/enemy_list.html"

    def get_context_data(self, **kwargs):
        context = {}
        enemies = models.EventEnemyParameter.objects.all()
        context["enemies"] = enemies
        return context

pcrd_unpack/views/json_views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from django.http import JsonResponse, HttpResponse, Http404
from django.db.models import Max, QuerySet

from django.core import serializers

class JSONResponseMixin:
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return JsonResponse(
            self.get_data(context),
            **response_kwargs
        )

    def get_data(self, context):
        """
        Returns an object that will be serialized as JSON by json.dumps().
        """
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return context

class UnitJsonView(JSONResponseMixin, TemplateView):
    """docstring for UnitJsonView"""
    def render_to_response(self, context, **response_kwargs):
        response_context = self.get_unit_data(context["unit_id"])
        return JsonResponse(response_context)

    def get_unit_data(self, unit_id=0):
        response_context = {}
        try:
            unit_data = models.UnitRarity.objects.filter(unit_id=unit_id).values()
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            unit_rank_data = models.UnitPromotionStatus.objects.filter(unit_id=unit_id).values()
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            unit_promotion_data_query = models.UnitPromotion.objects.filter(unit_id=unit_id).values()
            related_equipments = []
            unit_promotion_data =[]
            for i in unit_promotion_data_query:
                temp = []
                for j in range(1,7):
                    eq_id = i['equip_slot_{}'.format(j)]
                    related_equipments.append(eq_id)
                    temp.append(eq_id)
                unit_promotion_data.append(temp)
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            equipment_data = models.EquipmentData.objects.filter(equipment_id__in=related_equipments).values()
            equipment_data = {e["equipment_id"]: e for e in equipment_data}
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")


        try:
            equipment_enhance = models.EquipmentEnhanceRate.objects.filter(equipment_id__in=related_equipments).values()
            equipment_enhance = {e["equipment_id"]: e for e in equipment_enhance}
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        # enhance_table
        max_enhance = models.EquipmentEnhanceData.objects.aggregate(Max('promotion_level'))["promotion_level__max"]
        enhance_table = {i: models.EquipmentEnhanceData.objects.filter(promotion_level__exact=i).aggregate(Max('equipment_enhance_level'))["equipment_enhance_level__max"]
                         for i in range(2, max_enhance +1 )}

        # get love status bonus
        ls = models.CharaStoryStatus.objects.filter(chara_id_1__exact=int(unit_id / 100)).order_by('story_id')
        love_table = [self.reverse_love_status(l) for l in ls]
        response_context["unit_data"] = list(unit_data)
        response_context["unit_rank_data"] = list(unit_rank_data)
        response_context["unit_promotion_data"] = unit_promotion_data
        response_context["equipment_data"] = equipment_data
        response_context["equipment_enhance"] = equipment_enhance
        response_context["enhance_table"] = enhance_table
        response_context["love_table"] = love_table
        return response_context

    def reverse_love_status(self, love_status):
        ls_talbe = {}
        for i in range(1, 6):
            st = getattr(love_status, "status_type_{}".format(i))
            if st != 0:
                ls_talbe[models.GlobalStatus.love_status_map[st]] = getattr(love_status, "status_rate_{}".format(i))
        return ls_talbe

pcrd_unpack/views/solution_views.py
import json

from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden, request
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from itertools import zip_longest
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from collections import OrderedDict
import base64

def team_base_context():
    context = {
        'units': models.UnitData.available_unit().order_by('search_area_width'),
        "rarity_set": range(models.UnitSummary.max_rarity(), 0, -1),
    }
    return context

class SolutionView(TemplateView):
    template_name = "pcrd_unpack/solution/create_solution.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs, uri = request.build_absolute_uri())

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        solution_id = kwargs["solution_id"]
        solution = get_object_or_404(models.Solution, id=solution_id)
        context = {
            **team_base_context(),
            **{
                "left_team":solution.left_team.team_list,
                "left_rarity": solution.left_team.rarity_list,
                "right_team":solution.right_team.team_list,
                "right_rarity": solution.right_team.rarity_list,
                "share_link": kwargs["uri"],
                "solution": solution,
            },
        }
        return context

class CreateSolutionView(TemplateView):
    template_name = "pcrd_unpack/solution/create_solution.html"
    def get_context_data(self, **kwargs):
        # units = [models.UnitData.objects.get(unit_id=100101),
        #          models.UnitData.objects.get(unit_id=100102),]
        context = {
            **team_base_context(),
            **{
                "left_team":[""]*models.Team.UNITS_NUM,
                "left_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
                "right_team":[""]*models.Team.UNITS_NUM,
                "right_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
            },
        }
        return context

class SolutionIndexView(TemplateView):
    """docstring for SolutionIndexView"""
    template_name = "pcrd_unpack/solution/solution_index.html"
    def get_context_data(self, **kwargs):
        s_to_show = models.Solution.objects.order_by("-up_vote", "down_vote")[:5]
        context = {
                **team_base_context(),
                **{
                "solution": s_to_show
            },
        }
        return context

class SolutionSearchView(TemplateView):
    template_name = "pcrd_unpack/solution/solution_search.html"
    def post(self, request, *args, **kwargs):
        if request.body:
            data = json.loads(request.body.decode())
            context = self.get_context_data(**kwargs, data = data)
        else:
            context = self.get_context_data(**kwargs)

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        s_to_show = []
        if 'data' in kwargs:
            team = kwargs["data"]["team"]
            team_dict = {"right_team__unit_{}".format(i+1): u for i, u in enumerate(team) if u != ""}

            if team_dict:
                s_to_show = models.Solution.objects.filter(**team_dict).order_by("-up_vote", "down_vote")[:5]
        context = {
            **team_base_context(),
            **{
                "left_team":[""]*models.Team.UNITS_NUM,
                "left_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
                "solution": s_to_show
            },
        }
        return context


def create_solution_handler(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        # check whether it's valid:

        data = json.loads(request.body.decode())
        for key, value in data.items():
            if len(value) != models.Team.UNITS_NUM or None in value:
                 return HttpResponseForbidden()
        sid = create_solution(data["left_team"], data["left_rarity"], data["right_team"], data["right_rarity"])
        r = reverse("pcrd_unpack:solution", kwargs={"solution_id":sid})
        return HttpResponse(r)

def vote(request):
    if request.method == 'GET':
        target = request.META["HTTP_REFERER"].split("/")[-1]
        method = request.GET["method"]
        solution = get_object_or_404(models.Solution, id=target)
        if method == "up_vote":
            solution.up_vote += 1
        elif method == "down_vote":
            solution.down_vote += 1
        solution.save()
        return HttpResponse()


def create_solution(left_team:list, left_rarity:list, right_team:list, right_rarity:list):
    lt, created = models.Team.get_team(left_team, left_rarity)
    rt, created = models.Team.get_team(right_team, right_rarity)
    s = models.Solution(left_team=lt, right_team=rt)
    s.save()
    return s.id

pcrd_unpack/templates/pcrd_unpack/about.html
{% extends "pcrd_unpack/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

pcrd_unpack/templates/pcrd_unpack/index.html
{% extends "pcrd_unpack/layout.html" %}
{% load static %}
{% load i18n %}
{% block style_sheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'pcrd_unpack/content/album.css' %}"/>
    <style>
        a.custom-card,
        a.custom-card:hover {
            color: inherit;
            position: absolute;
            top: 0; left: 0;
            height: 100%; width: 100%;
        }
        body{display: block;}
    </style>
{% endblock %}

{% block content %}

    <div class="cover-container d-block h-100 p-3 mx-auto flex-column">
        <div class="masthead mb-auto">
        </div>
        <div role="main" class="inner cover text-center">
            <h1 class="cover-heading">{% trans "Princess Connect Re:Dive Wiki" %}</h1>
            <p class="lead text-muted">A wiki site provide Both Characters and Equipments data <br>
                However, this site is still under develop, connect me on <a href="https://github.com/PaleNeutron/Pcrd-Wiki">Github</a> if you find something wrong</p>

            <div class="card-deck">
                <div class="card bg-success">
                    <a class="custom-card" href="{% url 'pcrd_unpack:area' %}">
                    </a>
                    <img class="card-img-top" src="{% static "pcrd_unpack/Texture2D/icon_map.png" %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{% trans "Quest Areas" %}</h5>
                        <p class="card-text">{% trans "Quest maps with drop items and drop rates" %}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-white">{% trans "Hidden Drops Included" %}</small>
                    </div>
                </div>

                <div class="card bg-info">
                    <a class="custom-card" href="{% url 'pcrd_unpack:unit_list' %}">
                    </a>

                    <img class="card-img-top" src="{% static "pcrd_unpack/Texture2D/icon_unit.png" %}"
                         alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{% trans "Characters" %}</h5>
                        <p class="card-text">{% trans "Profile, Properties, Action Line, Sills, Equipments" %}<br>
                            {% trans "Get all you want to know with a character" %}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-white">{% trans "Enjoy & Analyse" %}</small>
                    </div>
                </div>

                <div class="card bg-secondary">
                    <a class="custom-card" href="{% url 'pcrd_unpack:equipment_list' %}">
                    </a>

                    <img class="card-img-top" src="{% static "pcrd_unpack/Texture2D/icon_equipment.png" %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{% trans "Equipments" %}</h5>
                        <p class="card-text">{% trans "List all Equipments here, You can find recipes and where to get them" %}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-white">{% trans "Review By-product in a Glances" %}</small>
                    </div>
                </div>
            </div>


            {#            <div class="lead">#}
            {#                <a class="btn btn-primary my-2" href="{% url 'pcrd_unpack:area' %}">Quest Areas</a>#}
            {##}
            {#                <a class="btn btn-primary my-2" href="{% url 'pcrd_unpack:equipment_list' %}">Equipments</a>#}
            {##}
            {#                <a class="btn btn-primary my-2" href="{% url 'pcrd_unpack:unit_list' %}">Characters</a>#}
            {##}
            {#                <a class="btn btn-primary my-2" href="{% url 'pcrd_unpack:unit_summary' %}">Characters Table</a>#}
            {##}
            {#                <a href="https://github.com/PaleNeutron/Pcrd-Wiki" class="btn btn-secondary my-2">Repo on Github</a>#}
            {#            </div>#}
        </div>
        <div class="masthead mb-auto">
        </div>
    </div>

{% endblock %}

pcrd_unpack/templates/pcrd_unpack/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
    {% block title %}
        {{ title|default:"Princess Connect Re:Dive Wiki" }}
    {% endblock %}
    </title>

    {% load static %}
    {% load i18n %}
    {% static 'pcrd_unpack/Texture2D/assets/_elementsresources/resources/icon/equipment' as equipment_icon_dir %}
    {% static 'pcrd_unpack/Texture2D/assets/_elementsresources/resources/icon/item' as item_icon_dir %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{#    <!-- Latest compiled and minified CSS -->#}
{#    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.0/bootstrap-table.min.css">#}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/fc-3.2.4/sc-1.4.4/datatables.min.css"/>

    {#    my css#}
    <link rel="stylesheet" type="text/css" href="{% static 'pcrd_unpack/content/site.css' %}" />
    {% block style_sheet %}
    {% endblock %}

    <link rel="icon" type="image/png" sizes="96x96" href="{%  static "favicon.png" %}">
{#    <script src="{% static 'pcrd_unpack/scripts/modernizr-2.6.2.js' %}"></script>#}
{#    track code for baidu#}
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-118363962-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-118363962-1');
    </script>
    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?37a09f690bf7d3a481a0545457463a29";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
</head>

<body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="top_nav">
        <a class="navbar-brand" href="{% url 'pcrd_unpack:index' %}">{% trans "Princess Connect Re:Dive Wiki" %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pcrd_unpack:area' %}">{% trans "Quest Areas" %}<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pcrd_unpack:equipment_list' %}">{% trans "Equipments" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pcrd_unpack:unit_list' %}">{% trans "Characters" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pcrd_unpack:unit_summary' %}">{% trans "Summary" %}</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pcrd_unpack:solution_index' %}">{% trans "Solutions" %}</a>
                    </li>
                {% endif %}

    {#            <li class="nav-item">#}
    {#                <a class="nav-link" href="{% url 'pcrd_unpack:item_list' %}">Items</a>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {#                <a class="nav-link" href="{% url 'pcrd_unpack:contact' %}">Contact</a>#}
    {#            </li>#}
    {#            <li class="nav-item dropdown">#}
    {#                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
    {#                    Dropdown#}
    {#                </a>#}
    {#                <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
    {#                    <a class="dropdown-item" href="#">Action</a>#}
    {#                    <a class="dropdown-item" href="#">Another action</a>#}
    {#                    <div class="dropdown-divider"></div>#}
    {#                    <a class="dropdown-item" href="#">Something else here</a>#}
    {#                </div>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {#                <a class="nav-link disabled" href="#">Disabled</a>#}
    {#            </li>#}
            </ul>
    {#        <form class="form-inline my-2 my-lg-0">#}
    {#            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
    {#            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
    {#        </form>#}
            {% include 'pcrd_unpack/loginpartial.html' %}
        </div>
    </nav>
    </header>
    <main>

        {% block body %}


        <div  class="container body-content">

        {% block content %}

        {% endblock %}
        {% endblock %}

        </div>
    </main>
    <footer class="footer px-5">
        <p class="mb-0">&copy; {{ year }} - {% trans "Princess Connect Re:Dive Wiki" %}</p>
    </footer>
    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
    <!-- Latest compiled and minified JavaScript -->
{#    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.0/bootstrap-table.min.js"></script>#}

    <!-- Latest compiled and minified Locales -->
{#    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.0/locale/bootstrap-table-zh-CN.min.js"></script>#}

{#    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>#}
{#    use bootstrap tooltip#}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.16/fc-3.2.4/sc-1.4.4/datatables.min.js"></script>
    <script type="text/javascript" src="{% static "pcrd_unpack/scripts/csrf_base_set.js" %}"></script>
{% block scripts %}

{% endblock %}

</body>
</html>