PcrdWiki/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.i18n import i18n_patterns

from pcrd_unpack.sitemaps import UnitSitemap, EquimpmentSitemap

sitemaps = {
    'unit': UnitSitemap,
    'equipment': EquimpmentSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
]

urlpatterns += i18n_patterns(
    path("", include("pcrd_unpack.urls")),
)

handler404 = 'pcrd_unpack.views.handler404'

pcrd_unpack/urls.py
from django.contrib import admin
from django.urls import path
import django.contrib.auth.views
from datetime import datetime
import pcrd_unpack.forms
from . import views


app_name = 'pcrd_unpack'

urlpatterns  = [
    path("", views.IndexView.as_view(), name="index"),
    path("unit_data/<int:unit_id>", views.UnitJsonView.as_view(), name="unit_json"),
    path("unit/<int:unit_id>", views.UnitDetailView.as_view(), name="unit"),
    path("unit/", views.UnitListView.as_view(), name="unit_list"),
    path("summary/", views.UnitSummaryView.as_view(), name="unit_summary"),
    path("item/<int:item_id>", views.ItemView.as_view(), name="item"),
    path("equipment_list/", views.EquipmentListView.as_view(), name="equipment_list"),
    path("area/", views.QuestAreaListView.as_view(), name="area"),
    path("area/<int:area_id>", views.QuestAreaDetailView.as_view(), name="area_detail"),
    path("equipment/<int:equipment_id>", views.EquipmentView.as_view(), name="equipment"),
    path("solution/create", views.CreateSolutionView.as_view(),name="create_solution"),
    path("solution/add", views.create_solution_handler, name="add_solution"),
    path("solution/search", views.SolutionSearchView.as_view(), name="search_solution"),
    path("solution/view/<str:solution_id>", views.SolutionView.as_view(), name="solution"),
    path("solution", views.SolutionIndexView.as_view(), name="solution_index"),
    path("enemy_list", views.EnemyListView.as_view(), name="enemy_list"),
    path("vote", views.vote, name="vote"),
    # path("404", views.handler404),
    path('login/',
         django.contrib.auth.views.login,
         {
             'template_name': 'pcrd_unpack/login.html',
             'authentication_form': pcrd_unpack.forms.BootstrapAuthenticationForm,
             'extra_context':
                 {
                     'title': 'Log in',
                     'year': datetime.now().year,
                 }
         },
         name='login'),
    path('logout',
         django.contrib.auth.views.logout,
         {
             'next_page': '/',
         },
         name='logout'),
]

pcrd_unpack/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse
from . import coop
# Create your views here.
from . import models

class EquipmentView(TemplateView):
    """docstring for """
    template_name = "pcrd_unpack/equipment.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        eq = get_object_or_404(models.EquipmentData, pk=self.kwargs["equipment_id"])
        context['equipment'] = eq
        drops = eq.questrewarddatacustom_set.all()
        quests = [i.quest for i in drops]
        context['drop_info'] = dict(zip(quests, [q.questrewarddatacustom_set.order_by('-rate') for q in quests]))
        if eq.craft_flg:
            cinfo =  get_object_or_404(models.EquipmentCraft, pk=self.kwargs["equipment_id"])
            context["craft_info"] = cinfo
            components = {}
            for i in range(1, 11):
                eqid = getattr(cinfo, "condition_equipment_id_{}".format(i))
                eq_num = getattr(cinfo, "consume_num_{}".format(i))
                if eqid:
                    components[eqid] = eq_num
            context["components"] = components
        return context

class EquipmentListView(ListView):
    """docstring for Equi"""
    template_name = "pcrd_unpack/equipment_list.html"
    # model = models.EquipmentData

    def get_queryset(self):
        return models.EquipmentData.objects.order_by("-promotion_level")

class ItemView(TemplateView):
    """docstring for """
    template_name = "pcrd_unpack/item.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = get_object_or_404(models.ItemData, pk=self.kwargs["item_id"])
        context['item'] = item
        drops = item.questrewarddatacustom_set.all()
        quests = [i.quest for i in drops]
        context['drop_info'] = dict(zip(quests, [q.questrewarddatacustom_set.order_by('-rate') for q in quests]))
        return context

# class ItemListView(ListView):
#     """docstring for Equi"""
#     template_name = "pcrd_unpack/item_list.html"
#     # model = models.EquipmentData
#
#     def get_queryset(self):
#         return models.ItemData.objects.order_by("-promotion_level")


class QuestAreaListView(ListView):
    """docstring for QuestAreaListView"""
    template_name = "pcrd_unpack/quests_list.html"
    model = models.QuestAreaData

class QuestAreaDetailView(TemplateView):
    """docstring for QuestAreaDetailView"""
    template_name = "pcrd_unpack/quest_area_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        area_id = self.kwargs["area_id"]
        area = get_object_or_404(models.QuestAreaData.objects, pk=area_id)
        context["area_title"] = area.area_name
        quests_in_charpter = models.QuestData.objects.filter(area_id=area_id)
        context["quests_in_charpter"] = quests_in_charpter
        context["quest_reward"] = {}
        for q in quests_in_charpter:
            context["quest_reward"][q] = q.questrewarddatacustom_set.order_by('-rate')
        return context

class UnitListView(ListView):
    """docstring for UnitListView"""
    template_name = "pcrd_unpack/unit_list.html"
    model = models.UnitData

    def get_queryset(self, **hints):
        return self.model.objects.exclude(comment__isnull=True).order_by("-rarity")



class UnitDetailView(TemplateView):
    """docstring for UnitDetailView"""
    template_name = "pcrd_unpack/unit_detail.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        unit_id = kwargs["unit_id"]
        unit_data = get_object_or_404(models.UnitData, pk=unit_id)
        unit_data.comment = unit_data.comment.replace("\\n", "\n")
        unit_profile = get_object_or_404(models.UnitProfile, pk=unit_id)
        unit_promotion = get_list_or_404(models.UnitPromotion, pk=unit_id)
        context["unit_data"] = unit_data
        context["unit_profile"] = unit_profile
        context["unit_promotion"] = unit_promotion
        return context




def handler404(request, exception):
    return render(request, 'pcrd_unpack/errors/404.html', locals())

pcrd_unpack/views/enemy_view.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from itertools import zip_longest
from django.http import HttpResponseNotFound
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from collections import OrderedDict
from pcrd_unpack.utils import skill_utility


class EnemyListView(TemplateView):
    """docstring for EnemyListView"""
    template_name = "pcrd_unpack/enemy/enemy_list.html"

    def get_context_data(self, **kwargs):
        context = {}
        enemies = models.EventEnemyParameter.objects.all()
        context["enemies"] = enemies
        return context

pcrd_unpack/views/json_views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from django.http import JsonResponse, HttpResponse, Http404
from django.db.models import Max, QuerySet

from django.core import serializers

class JSONResponseMixin:
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return JsonResponse(
            self.get_data(context),
            **response_kwargs
        )

    def get_data(self, context):
        """
        Returns an object that will be serialized as JSON by json.dumps().
        """
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return context

class UnitJsonView(JSONResponseMixin, TemplateView):
    """docstring for UnitJsonView"""
    def render_to_response(self, context, **response_kwargs):
        response_context = self.get_unit_data(context["unit_id"])
        return JsonResponse(response_context)

    def get_unit_data(self, unit_id=0):
        response_context = {}
        try:
            unit_data = models.UnitRarity.objects.filter(unit_id=unit_id).values()
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            unit_rank_data = models.UnitPromotionStatus.objects.filter(unit_id=unit_id).values()
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            unit_promotion_data_query = models.UnitPromotion.objects.filter(unit_id=unit_id).values()
            related_equipments = []
            unit_promotion_data =[]
            for i in unit_promotion_data_query:
                temp = []
                for j in range(1,7):
                    eq_id = i['equip_slot_{}'.format(j)]
                    related_equipments.append(eq_id)
                    temp.append(eq_id)
                unit_promotion_data.append(temp)
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            equipment_data = models.EquipmentData.objects.filter(equipment_id__in=related_equipments).values()
            equipment_data = {e["equipment_id"]: e for e in equipment_data}
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")


        try:
            equipment_enhance = models.EquipmentEnhanceRate.objects.filter(equipment_id__in=related_equipments).values()
            equipment_enhance = {e["equipment_id"]: e for e in equipment_enhance}
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        # enhance_table
        max_enhance = models.EquipmentEnhanceData.objects.aggregate(Max('promotion_level'))["promotion_level__max"]
        enhance_table = {i: models.EquipmentEnhanceData.objects.filter(promotion_level__exact=i).aggregate(Max('equipment_enhance_level'))["equipment_enhance_level__max"]
                         for i in range(2, max_enhance +1 )}

        # get love status bonus
        ls = models.CharaStoryStatus.objects.filter(chara_id_1__exact=int(unit_id / 100)).order_by('story_id')
        love_table = [self.reverse_love_status(l) for l in ls]
        response_context["unit_data"] = list(unit_data)
        response_context["unit_rank_data"] = list(unit_rank_data)
        response_context["unit_promotion_data"] = unit_promotion_data
        response_context["equipment_data"] = equipment_data
        response_context["equipment_enhance"] = equipment_enhance
        response_context["enhance_table"] = enhance_table
        response_context["love_table"] = love_table
        return response_context

    def reverse_love_status(self, love_status):
        ls_talbe = {}
        for i in range(1, 6):
            st = getattr(love_status, "status_type_{}".format(i))
            if st != 0:
                ls_talbe[models.GlobalStatus.love_status_map[st]] = getattr(love_status, "status_rate_{}".format(i))
        return ls_talbe

pcrd_unpack/views/solution_views.py
import json

from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden, request
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from itertools import zip_longest
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from collections import OrderedDict
import base64

def team_base_context():
    context = {
        'units': models.UnitData.available_unit().order_by('search_area_width'),
        "rarity_set": range(models.UnitSummary.max_rarity(), 0, -1),
    }
    return context

class SolutionView(TemplateView):
    template_name = "pcrd_unpack/solution/create_solution.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs, uri = request.build_absolute_uri())

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        solution_id = kwargs["solution_id"]
        solution = get_object_or_404(models.Solution, id=solution_id)
        context = {
            **team_base_context(),
            **{
                "left_team":solution.left_team.team_list,
                "left_rarity": solution.left_team.rarity_list,
                "right_team":solution.right_team.team_list,
                "right_rarity": solution.right_team.rarity_list,
                "share_link": kwargs["uri"],
                "solution": solution,
            },
        }
        return context

class CreateSolutionView(TemplateView):
    template_name = "pcrd_unpack/solution/create_solution.html"
    def get_context_data(self, **kwargs):
        # units = [models.UnitData.objects.get(unit_id=100101),
        #          models.UnitData.objects.get(unit_id=100102),]
        context = {
            **team_base_context(),
            **{
                "left_team":[""]*models.Team.UNITS_NUM,
                "left_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
                "right_team":[""]*models.Team.UNITS_NUM,
                "right_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
            },
        }
        return context

class SolutionIndexView(TemplateView):
    """docstring for SolutionIndexView"""
    template_name = "pcrd_unpack/solution/solution_index.html"
    def get_context_data(self, **kwargs):
        s_to_show = models.Solution.objects.order_by("-up_vote", "down_vote")[:5]
        context = {
                **team_base_context(),
                **{
                "solution": s_to_show
            },
        }
        return context

class SolutionSearchView(TemplateView):
    template_name = "pcrd_unpack/solution/solution_search.html"
    def post(self, request, *args, **kwargs):
        if request.body:
            data = json.loads(request.body.decode())
            context = self.get_context_data(**kwargs, data = data)
        else:
            context = self.get_context_data(**kwargs)

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        s_to_show = []
        if 'data' in kwargs:
            team = kwargs["data"]["team"]
            team_dict = {"right_team__unit_{}".format(i+1): u for i, u in enumerate(team) if u != ""}

            if team_dict:
                s_to_show = models.Solution.objects.filter(**team_dict).order_by("-up_vote", "down_vote")[:5]
        context = {
            **team_base_context(),
            **{
                "left_team":[""]*models.Team.UNITS_NUM,
                "left_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
                "solution": s_to_show
            },
        }
        return context


def create_solution_handler(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        # check whether it's valid:

        data = json.loads(request.body.decode())
        for key, value in data.items():
            if len(value) != models.Team.UNITS_NUM or None in value:
                 return HttpResponseForbidden()
        sid = create_solution(data["left_team"], data["left_rarity"], data["right_team"], data["right_rarity"])
        r = reverse("pcrd_unpack:solution", kwargs={"solution_id":sid})
        return HttpResponse(r)

def vote(request):
    if request.method == 'GET':
        target = request.META["HTTP_REFERER"].split("/")[-1]
        method = request.GET["method"]
        solution = get_object_or_404(models.Solution, id=target)
        if method == "up_vote":
            solution.up_vote += 1
        elif method == "down_vote":
            solution.down_vote += 1
        solution.save()
        return HttpResponse()


def create_solution(left_team:list, left_rarity:list, right_team:list, right_rarity:list):
    lt, created = models.Team.get_team(left_team, left_rarity)
    rt, created = models.Team.get_team(right_team, right_rarity)
    s = models.Solution(left_team=lt, right_team=rt)
    s.save()
    return s.id

pcrd_unpack/templates/pcrd_unpack/solution/create_solution.html
{% extends "pcrd_unpack/layout.html" %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans "Create Solution" %} - {% trans "Princess Connect Re:Dive Wiki" %}
{% endblock %}

{% block style_sheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'pcrd_unpack/content/team_deck.css' %}" />
{% endblock %}

{% block content %}
    {% if share_link %}
        <div class="row justify-content-center">
            <div class="input-group my-5 input-group-lg col-10">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">Your Share Link</span>
                </div>
                <input type="text" class="form-control" readonly placeholder="Share Link" aria-label="Share Link" aria-describedby="basic-addon1" value="{{ share_link }}">
            </div>
        </div>
    {% endif %}

    <div class="container my-3">
        <div class="row justify-content-end">
            <div class="col-10">
                {% include "pcrd_unpack/solution/team_deck.html" with team="right" team_num=right_team rarities=right_rarity%}
            </div>
        </div>
        <div class="row justify-content-center m-3">
            <h2>VS</h2>
        </div>
        <div class="row">
            <div class="col-10">
                {% include "pcrd_unpack/solution/team_deck.html" with team="left" team_num=left_team rarities=left_rarity %}
            </div>
        </div>
    </div>

    <div class="row justify-content-center ">
        <div class="row col-8">
            {% if share_link %}
                <div class="mr-3">
                    <button type="button" class="btn btn-success btn-lg active" id="up_vote_btn">▲ {{ solution.up_vote }}</button>
                </div>
                <div class="mr-auto">
                    <button type="button" class="btn btn-warning btn-lg active mr-auto" id="down_vote_btn">▼ {{ solution.down_vote }}</button>
                </div>
            {% endif %}
            <button type="button" class="btn btn-primary btn-lg active ml-auto" id="share_btn" aria-disabled="false">Create Share Link</button>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {% static "pcrd_unpack/Texture2D/assets/_elementsresources/resources/unit/icon" as unit_icon %}
    <script>
        {% autoescape off %}
            var left_team = {{ left_team }};
            var left_rarity = {{ left_rarity }};
            var right_team = {{ left_team }};
            var right_rarity = {{ right_rarity }};
            var unit_icon_path = "{{ unit_icon }}";
        {% endautoescape %}
        var add_solution_url = "{% url "pcrd_unpack:add_solution" %}";
        var vote_url = "{% url "pcrd_unpack:vote" %}";
    </script>
    <script type="text/javascript" src="{% static "pcrd_unpack/scripts/elements/ShareSolution.js" %}"></script>
    <script type="text/javascript" src="{% static "pcrd_unpack/scripts/elements/UnitSelector.js" %}"></script>
{% endblock %}

pcrd_unpack/templates/pcrd_unpack/solution/solution_index.html
{% extends "pcrd_unpack/layout.html" %}
{% load static %}
{% load i18n %}


{% block style_sheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'pcrd_unpack/content/team_deck.css' %}" />
    <style>
    body .btn h2{
        font-size: 3vw;
    }
    #search_area .nav{
        padding-top: 200px;
    }
    #search_area {
        max-width: 107px;
        min-width: 42px;
    }
    body .solution_item{
        overflow: hidden;
    }
    @media (max-width: 576px) {
        body .btn h2{
            font-size: 30px ;
        }

        a.nav-link {
            padding-left: 1px;
        }
        #search_area {
            padding-left: 2px;
            padding-right: 2px;
        }
    }
    </style>
{% endblock %}

{% block body %}
    <div class="d-flex flex-row">
    <div class="col-2 bg-dark  navbar-dark " id="search_area">

{#            <div class="my-5 d-none d-md-block" id="nav_spacer"></div>#}
{##}
{#            <div class="mb-auto"><a class="btn btn-primary btn-lg btn-block" href="{% url "pcrd_unpack:create_solution" %}"><h2>Create</h2></a></div>#}
{#            <div class="my-1 my-md-5"><a class="btn btn-secondary btn-lg btn-block disabled"  href="#"><h2>Search</h2></a></div>#}
{#        #}
            <ul class="nav navbar-nav flex-column  nav-pills sticky-top">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "pcrd_unpack:create_solution" %}">Create</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "pcrd_unpack:search_solution" %}">Search</a>
                </li>
            </ul>
    </div>
    <div class="col-10 justify-content-between ">
        <div class="row justify-content-center m-3">
            <h1>Solutions</h1>
        </div>
        <div class="row">
            <div class="col">
                <div class="row justify-content-center m-2">
                    <h2>Top Voted</h2>
                </div>
                {% include "pcrd_unpack/solution/solutions_table.html" %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
    function go_to_solution(e) {
        window.location.href = $(e).attr("content");
    }
    </script>
{% endblock %}

pcrd_unpack/templates/pcrd_unpack/solution/solution_search.html
{% extends "pcrd_unpack/layout.html" %}
{% load static %}
{% load i18n %}

{% block style_sheet %}
<link rel="stylesheet" type="text/css" href="{% static 'pcrd_unpack/content/team_deck.css' %}" />
{% endblock %}

{% block content %}
    <div class="row mb-md-5"></div>
    {% include "pcrd_unpack/solution/team_deck.html" with team="left" team_num=left_team rarities=left_rarity %}
    <div class="row col-10 justify-content-end my-3">
            <button type="submit" class="btn btn-lg btn-primary" id="btn_search" value="submit_value">Search</button>

    </div>
    <div  id="solution_search_result">
    {% if solution %}
        <hr>
        <div class="row justify-content-center"><h2>Search Result</h2></div>
        {% include "pcrd_unpack/solution/solutions_table.html" %}

    {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    {% static "pcrd_unpack/Texture2D/assets/_elementsresources/resources/unit/icon" as unit_icon %}
    <script>
        {% autoescape off %}
            var left_team = {{ left_team }};
            var left_rarity = {{ left_rarity }};
            var unit_icon_path = "{{ unit_icon }}";
        {% endautoescape %}
        var search_url = "{% url "pcrd_unpack:search_solution" %}";
    </script>

    <script type="text/javascript" src="{% static "pcrd_unpack/scripts/elements/SearchSolution.js" %}"></script>
    <script type="text/javascript" src="{% static "pcrd_unpack/scripts/elements/ShareSolution.js" %}"></script>
    <script type="text/javascript" src="{% static "pcrd_unpack/scripts/elements/UnitSelector.js" %}"></script>
{% endblock %}

pcrd_unpack/templates/pcrd_unpack/solution/solutions_table.html
<div>
    {% for s in solution %}

        <div class="col btn-light btn solution_item"  content="{% url "pcrd_unpack:solution" s.id %}" onclick="go_to_solution(this)">
            {#                            <a class="d-block w-100 h-100 " href="{% url "pcrd_unpack:solution" s.id %}"></a>#}

            <div class="row justify-content-between px-4">
                <div class="col-md-5 p-0">
                    {% include "pcrd_unpack/solution/team_deck.html" with team_num=s.left_team.team_list rarities=s.left_team.rarity_list disabled=True %}
                </div>
                <div class="col-md-2 row align-items-center">
                    <div class="col text text-dark text-center font-weight-bold" style="font-size: 2vw">V.S.</div>
                </div>
                <div class="col-md-5 p-0">
                    {% include "pcrd_unpack/solution/team_deck.html" with team_num=s.right_team.team_list rarities=s.right_team.rarity_list disabled=True %}
                </div>
                <div class="row justify-content-start p-md-2">
                    <div  class="btn-group btn-group-sm ml-4 ml-md-0" role="group" >
                        <button type="button" class="btn btn-success btn-sm">▲ {{ s.up_vote }}</button>
                        <button type="button" class="btn btn-warning btn-sm">▼ {{ s.down_vote }}</button>
                    </div>
                </div>
            </div>

        </div>


        {% if not forloop.last %}
            <hr>
        {% endif %}
    {% endfor %}
</div>

pcrd_unpack/templates/pcrd_unpack/solution/team_deck.html
{% load static %}
{% load custom_tags %}
{#specific team_units rarities to init#}
{#use disabled to make it not editable#}

{% static "pcrd_unpack/Texture2D/assets/_elementsresources/resources/unit/icon" as unit_icon %}
<div class="row d-block">
<div class="d-none">{{ team_num.reverse }}{{ rarities.reverse }}</div>
<div class="row justify-content-center team-container mx-0">
    <div class="card-group flex-row">
        {% for unit_id in team_num %}
            {% with forloop.counter0 as i %}

                <div class="card bg-light">
                    <div hidden class="storage"></div>
{#                    <a class="custom-card" href="{% url 'pcrd_unpack:area' %}">#}
{#                    </a>#}
                    <img class="card-img-top" {% if team %}id="unit_img_{{ team }}_{{ forloop.revcounter }}"{% endif %}
                            {% if unit_id %}
                         src="{{ unit_icon }}/icon_unit_{% if rarities|index:forloop.counter0 >= 3 %}{{ unit_id|add:"30" }}{% else %}{{ unit_id|add:"10" }}{% endif %}.jpg"
                            {% else %}
                         src="{% static "pcrd_unpack/Texture2D/assets/_elementsresources/resources/unit/icon/icon_unit_unknown.jpg" %}"
                            {% endif %}
                         alt="Card image cap">
                    <hr>

                    <div class="card-body">
                        {% if disabled %}
                            {% with rarities|index:i as r %}
                                <div class="text-center font-weight-bold"> {% for x in ""|ljust:r %}★{% endfor %} </div>

                            {% endwith %}
                        {% else %}
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle  w-100" type="button"
                                    {% if team %}id="dropdownMenuButton_{{ team }}"{% endif %} data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                Unit {{ forloop.revcounter }}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"
                                 {% if team %}id="unit_select_{{ team }}_{{ forloop.revcounter }}"{% endif %}>
                                {% for unit in units %}
                                    <a class="dropdown-item btn"><span hidden
                                                                   class="storage">{{ unit.unit_id }}</span><img
                                            class="img-thumbnail w-50 h-50" src="{{ unit_icon }}/icon_unit_{% if unit.rarity == 3 %}{{ unit.unit_id|add:"30" }}{% else %}{{ unit.unit_id|add:"10" }}{% endif %}.jpg"
                                            alt="">{{ unit.unit_name }}</a>
                                {% endfor %}
                            </div>
                            <div>
                                <select class="form-control unit_rarity_selector"
                                        {% if team %}id="unit_rarity_select_{{ team }}_{{ forloop.revcounter }}{% endif %}"
                                        title="unit_rarity_select_{{ team }}_{{ forloop.revcounter }}">
                                    {% for r in rarity_set %}
                                        <option value="{{ r }}" {% if rarities|index:i == r %}
                                                selected
                                        {% endif %} >{% for x in ""|ljust:r %}★{% endfor %}</option>
                                    {% endfor %}
                                </select>

                            </div>
                        </div>
                        {% endif %}
                    </div>
                    {#                <div class="card-footer">#}
                    {#                    <small class="text-white">Hidden Drops Included</small>#}
                    {#                </div>#}
                </div>
            {% endwith %}
        {% endfor %}
    </div>
</div>
</div>