PcrdWiki/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.i18n import i18n_patterns

from pcrd_unpack.sitemaps import UnitSitemap, EquimpmentSitemap

sitemaps = {
    'unit': UnitSitemap,
    'equipment': EquimpmentSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
]

urlpatterns += i18n_patterns(
    path("", include("pcrd_unpack.urls")),
)

handler404 = 'pcrd_unpack.views.handler404'

pcrd_unpack/urls.py
from django.contrib import admin
from django.urls import path
import django.contrib.auth.views
from datetime import datetime
import pcrd_unpack.forms
from . import views


app_name = 'pcrd_unpack'

urlpatterns  = [
    path("", views.IndexView.as_view(), name="index"),
    path("unit_data/<int:unit_id>", views.UnitJsonView.as_view(), name="unit_json"),
    path("unit/<int:unit_id>", views.UnitDetailView.as_view(), name="unit"),
    path("unit/", views.UnitListView.as_view(), name="unit_list"),
    path("summary/", views.UnitSummaryView.as_view(), name="unit_summary"),
    path("item/<int:item_id>", views.ItemView.as_view(), name="item"),
    path("equipment_list/", views.EquipmentListView.as_view(), name="equipment_list"),
    path("area/", views.QuestAreaListView.as_view(), name="area"),
    path("area/<int:area_id>", views.QuestAreaDetailView.as_view(), name="area_detail"),
    path("equipment/<int:equipment_id>", views.EquipmentView.as_view(), name="equipment"),
    path("solution/create", views.CreateSolutionView.as_view(),name="create_solution"),
    path("solution/add", views.create_solution_handler, name="add_solution"),
    path("solution/search", views.SolutionSearchView.as_view(), name="search_solution"),
    path("solution/view/<str:solution_id>", views.SolutionView.as_view(), name="solution"),
    path("solution", views.SolutionIndexView.as_view(), name="solution_index"),
    path("enemy_list", views.EnemyListView.as_view(), name="enemy_list"),
    path("vote", views.vote, name="vote"),
    # path("404", views.handler404),
    path('login/',
         django.contrib.auth.views.login,
         {
             'template_name': 'pcrd_unpack/login.html',
             'authentication_form': pcrd_unpack.forms.BootstrapAuthenticationForm,
             'extra_context':
                 {
                     'title': 'Log in',
                     'year': datetime.now().year,
                 }
         },
         name='login'),
    path('logout',
         django.contrib.auth.views.logout,
         {
             'next_page': '/',
         },
         name='logout'),
]

pcrd_unpack/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse
from . import coop
# Create your views here.
from . import models

class EquipmentView(TemplateView):
    """docstring for """
    template_name = "pcrd_unpack/equipment.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        eq = get_object_or_404(models.EquipmentData, pk=self.kwargs["equipment_id"])
        context['equipment'] = eq
        drops = eq.questrewarddatacustom_set.all()
        quests = [i.quest for i in drops]
        context['drop_info'] = dict(zip(quests, [q.questrewarddatacustom_set.order_by('-rate') for q in quests]))
        if eq.craft_flg:
            cinfo =  get_object_or_404(models.EquipmentCraft, pk=self.kwargs["equipment_id"])
            context["craft_info"] = cinfo
            components = {}
            for i in range(1, 11):
                eqid = getattr(cinfo, "condition_equipment_id_{}".format(i))
                eq_num = getattr(cinfo, "consume_num_{}".format(i))
                if eqid:
                    components[eqid] = eq_num
            context["components"] = components
        return context

class EquipmentListView(ListView):
    """docstring for Equi"""
    template_name = "pcrd_unpack/equipment_list.html"
    # model = models.EquipmentData

    def get_queryset(self):
        return models.EquipmentData.objects.order_by("-promotion_level")

class ItemView(TemplateView):
    """docstring for """
    template_name = "pcrd_unpack/item.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = get_object_or_404(models.ItemData, pk=self.kwargs["item_id"])
        context['item'] = item
        drops = item.questrewarddatacustom_set.all()
        quests = [i.quest for i in drops]
        context['drop_info'] = dict(zip(quests, [q.questrewarddatacustom_set.order_by('-rate') for q in quests]))
        return context

# class ItemListView(ListView):
#     """docstring for Equi"""
#     template_name = "pcrd_unpack/item_list.html"
#     # model = models.EquipmentData
#
#     def get_queryset(self):
#         return models.ItemData.objects.order_by("-promotion_level")


class QuestAreaListView(ListView):
    """docstring for QuestAreaListView"""
    template_name = "pcrd_unpack/quests_list.html"
    model = models.QuestAreaData

class QuestAreaDetailView(TemplateView):
    """docstring for QuestAreaDetailView"""
    template_name = "pcrd_unpack/quest_area_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        area_id = self.kwargs["area_id"]
        area = get_object_or_404(models.QuestAreaData.objects, pk=area_id)
        context["area_title"] = area.area_name
        quests_in_charpter = models.QuestData.objects.filter(area_id=area_id)
        context["quests_in_charpter"] = quests_in_charpter
        context["quest_reward"] = {}
        for q in quests_in_charpter:
            context["quest_reward"][q] = q.questrewarddatacustom_set.order_by('-rate')
        return context

class UnitListView(ListView):
    """docstring for UnitListView"""
    template_name = "pcrd_unpack/unit_list.html"
    model = models.UnitData

    def get_queryset(self, **hints):
        return self.model.objects.exclude(comment__isnull=True).order_by("-rarity")



class UnitDetailView(TemplateView):
    """docstring for UnitDetailView"""
    template_name = "pcrd_unpack/unit_detail.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        unit_id = kwargs["unit_id"]
        unit_data = get_object_or_404(models.UnitData, pk=unit_id)
        unit_data.comment = unit_data.comment.replace("\\n", "\n")
        unit_profile = get_object_or_404(models.UnitProfile, pk=unit_id)
        unit_promotion = get_list_or_404(models.UnitPromotion, pk=unit_id)
        context["unit_data"] = unit_data
        context["unit_profile"] = unit_profile
        context["unit_promotion"] = unit_promotion
        return context




def handler404(request, exception):
    return render(request, 'pcrd_unpack/errors/404.html', locals())

pcrd_unpack/views/enemy_view.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from itertools import zip_longest
from django.http import HttpResponseNotFound
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from collections import OrderedDict
from pcrd_unpack.utils import skill_utility


class EnemyListView(TemplateView):
    """docstring for EnemyListView"""
    template_name = "pcrd_unpack/enemy/enemy_list.html"

    def get_context_data(self, **kwargs):
        context = {}
        enemies = models.EventEnemyParameter.objects.all()
        context["enemies"] = enemies
        return context

pcrd_unpack/views/json_views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from django.http import JsonResponse, HttpResponse, Http404
from django.db.models import Max, QuerySet

from django.core import serializers

class JSONResponseMixin:
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return JsonResponse(
            self.get_data(context),
            **response_kwargs
        )

    def get_data(self, context):
        """
        Returns an object that will be serialized as JSON by json.dumps().
        """
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return context

class UnitJsonView(JSONResponseMixin, TemplateView):
    """docstring for UnitJsonView"""
    def render_to_response(self, context, **response_kwargs):
        response_context = self.get_unit_data(context["unit_id"])
        return JsonResponse(response_context)

    def get_unit_data(self, unit_id=0):
        response_context = {}
        try:
            unit_data = models.UnitRarity.objects.filter(unit_id=unit_id).values()
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            unit_rank_data = models.UnitPromotionStatus.objects.filter(unit_id=unit_id).values()
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            unit_promotion_data_query = models.UnitPromotion.objects.filter(unit_id=unit_id).values()
            related_equipments = []
            unit_promotion_data =[]
            for i in unit_promotion_data_query:
                temp = []
                for j in range(1,7):
                    eq_id = i['equip_slot_{}'.format(j)]
                    related_equipments.append(eq_id)
                    temp.append(eq_id)
                unit_promotion_data.append(temp)
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        try:
            equipment_data = models.EquipmentData.objects.filter(equipment_id__in=related_equipments).values()
            equipment_data = {e["equipment_id"]: e for e in equipment_data}
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")


        try:
            equipment_enhance = models.EquipmentEnhanceRate.objects.filter(equipment_id__in=related_equipments).values()
            equipment_enhance = {e["equipment_id"]: e for e in equipment_enhance}
        except models.UnitRarity.DoesNotExist:
            raise Http404("unit not found")

        # enhance_table
        max_enhance = models.EquipmentEnhanceData.objects.aggregate(Max('promotion_level'))["promotion_level__max"]
        enhance_table = {i: models.EquipmentEnhanceData.objects.filter(promotion_level__exact=i).aggregate(Max('equipment_enhance_level'))["equipment_enhance_level__max"]
                         for i in range(2, max_enhance +1 )}

        # get love status bonus
        ls = models.CharaStoryStatus.objects.filter(chara_id_1__exact=int(unit_id / 100)).order_by('story_id')
        love_table = [self.reverse_love_status(l) for l in ls]
        response_context["unit_data"] = list(unit_data)
        response_context["unit_rank_data"] = list(unit_rank_data)
        response_context["unit_promotion_data"] = unit_promotion_data
        response_context["equipment_data"] = equipment_data
        response_context["equipment_enhance"] = equipment_enhance
        response_context["enhance_table"] = enhance_table
        response_context["love_table"] = love_table
        return response_context

    def reverse_love_status(self, love_status):
        ls_talbe = {}
        for i in range(1, 6):
            st = getattr(love_status, "status_type_{}".format(i))
            if st != 0:
                ls_talbe[models.GlobalStatus.love_status_map[st]] = getattr(love_status, "status_rate_{}".format(i))
        return ls_talbe

pcrd_unpack/views/solution_views.py
import json

from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden, request
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from django.shortcuts import get_list_or_404, get_object_or_404
from itertools import zip_longest
from django.urls import reverse
# Create your views here.
from pcrd_unpack import models
from collections import OrderedDict
import base64

def team_base_context():
    context = {
        'units': models.UnitData.available_unit().order_by('search_area_width'),
        "rarity_set": range(models.UnitSummary.max_rarity(), 0, -1),
    }
    return context

class SolutionView(TemplateView):
    template_name = "pcrd_unpack/solution/create_solution.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs, uri = request.build_absolute_uri())

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        solution_id = kwargs["solution_id"]
        solution = get_object_or_404(models.Solution, id=solution_id)
        context = {
            **team_base_context(),
            **{
                "left_team":solution.left_team.team_list,
                "left_rarity": solution.left_team.rarity_list,
                "right_team":solution.right_team.team_list,
                "right_rarity": solution.right_team.rarity_list,
                "share_link": kwargs["uri"],
                "solution": solution,
            },
        }
        return context

class CreateSolutionView(TemplateView):
    template_name = "pcrd_unpack/solution/create_solution.html"
    def get_context_data(self, **kwargs):
        # units = [models.UnitData.objects.get(unit_id=100101),
        #          models.UnitData.objects.get(unit_id=100102),]
        context = {
            **team_base_context(),
            **{
                "left_team":[""]*models.Team.UNITS_NUM,
                "left_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
                "right_team":[""]*models.Team.UNITS_NUM,
                "right_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
            },
        }
        return context

class SolutionIndexView(TemplateView):
    """docstring for SolutionIndexView"""
    template_name = "pcrd_unpack/solution/solution_index.html"
    def get_context_data(self, **kwargs):
        s_to_show = models.Solution.objects.order_by("-up_vote", "down_vote")[:5]
        context = {
                **team_base_context(),
                **{
                "solution": s_to_show
            },
        }
        return context

class SolutionSearchView(TemplateView):
    template_name = "pcrd_unpack/solution/solution_search.html"
    def post(self, request, *args, **kwargs):
        if request.body:
            data = json.loads(request.body.decode())
            context = self.get_context_data(**kwargs, data = data)
        else:
            context = self.get_context_data(**kwargs)

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        s_to_show = []
        if 'data' in kwargs:
            team = kwargs["data"]["team"]
            team_dict = {"right_team__unit_{}".format(i+1): u for i, u in enumerate(team) if u != ""}

            if team_dict:
                s_to_show = models.Solution.objects.filter(**team_dict).order_by("-up_vote", "down_vote")[:5]
        context = {
            **team_base_context(),
            **{
                "left_team":[""]*models.Team.UNITS_NUM,
                "left_rarity": [models.UnitSummary.max_rarity()]*models.Team.UNITS_NUM,
                "solution": s_to_show
            },
        }
        return context


def create_solution_handler(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        # check whether it's valid:

        data = json.loads(request.body.decode())
        for key, value in data.items():
            if len(value) != models.Team.UNITS_NUM or None in value:
                 return HttpResponseForbidden()
        sid = create_solution(data["left_team"], data["left_rarity"], data["right_team"], data["right_rarity"])
        r = reverse("pcrd_unpack:solution", kwargs={"solution_id":sid})
        return HttpResponse(r)

def vote(request):
    if request.method == 'GET':
        target = request.META["HTTP_REFERER"].split("/")[-1]
        method = request.GET["method"]
        solution = get_object_or_404(models.Solution, id=target)
        if method == "up_vote":
            solution.up_vote += 1
        elif method == "down_vote":
            solution.down_vote += 1
        solution.save()
        return HttpResponse()


def create_solution(left_team:list, left_rarity:list, right_team:list, right_rarity:list):
    lt, created = models.Team.get_team(left_team, left_rarity)
    rt, created = models.Team.get_team(right_team, right_rarity)
    s = models.Solution(left_team=lt, right_team=rt)
    s.save()
    return s.id

pcrd_unpack/templates/pcrd_unpack/summary/unit_summary.html
{% extends "pcrd_unpack/layout.html" %}
{% load static %}
{% load i18n %}


{% block title %}
    {%  trans "Summary"%}-{%  trans "Princess Connect Re:Dive Wiki"%}
{% endblock %}
{% block style_sheet %}
    <style>
    {#show table after init#}
    #unit_summary_list {
        visibility: hidden;
    }

    #unit_summary_list_wrapper #unit_summary_list{
        visibility: visible;
    }

    #unit_summary_list_wrapper th{
        white-space: nowrap;
    }
    </style>
{% endblock %}

{% block content %}
    {% static "pcrd_unpack/Texture2D/assets/_elementsresources/resources/unit/icon" as unit_icon %}
{#    {% static "pcrd_unpack/Texture2D/assets/_elementsresources/resources/icon/unitplate/" as unitplate %}#}

    <div class="jumbotron-fluid h-100">
        <h1 class="display-4">
            {% trans "Summary Data" %}</h1>
    </div>

    <hr>
    <div class="col justify-content-center">
        <h2 class="text-center">{% trans "Unit Maxim Data" %}</h2>
        <hr class="my-4">
        <p class="lead">{% trans "Units Data at" %} {% trans "Level" %} {{ max_level }}, {% trans "Rank" %} {{ max_rank }},
            {% trans "Star" %} {{ max_rarity }}, {% trans "Love Level" %} {{ max_love }}
            {% trans "with fully enhanced equipments" %}</p>
    </div>
    <div class="row">
        <table class="table table-sm table-bordered table-hover"  id="unit_summary_list">
        <thead class="thead-dark">
        <tr>
            <th>PIC</th>
            <th>Name</th>
            {% for data_tag in data_tags %}
                <th>{% trans data_tag  %}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
            {% for unitsummary, unit_summary_data in unit_summary_data.items %}
                <tr>
                    <th>
                        <a href="{% url "pcrd_unpack:unit" unitsummary.unit_id %}">
                            <img class="rounded d-block w-100"
                                 src="{{ unit_icon }}/icon_unit_{% if unitsummary.unit.rarity == 3 %}{{ unitsummary.unit.unit_id|add:"30" }}{% else %}{{ unitsummary.unit.unit_id|add:"10" }}{% endif %}.jpg" alt="">
                        </a>
                    </th>
                    <td>
                        {{ unitsummary.unit.unit_name }}
                    </td>
                        {% for unit_summary_datum in unit_summary_data %}
                            <td>
                            {{ unit_summary_datum}}
                            </td>
                        {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>

    <hr>
    <div class="row justify-content-center">
    <h2>{% trans "Experience Analyse" %}</h2>
    </div>
    <div class="container row d-flex">
        <div class="container col-md-5 col-sm-12">
            <canvas id="exp_chart" width="400" height="400"></canvas>
        </div>
        <div class="container col-md-5 col-sm-12">
            <canvas id="exp_compare_chart" width="400" height="400"></canvas>
        </div>

    </div>
    <div class="row justify-content-center">
        <h2>{% trans "Mana Analyse" %}</h2>
    </div>
    <div class="container row d-flex">
        <div class="container col-md-5 col-sm-12">
            <canvas id="skill_mana_chart" width="400" height="400"></canvas>
        </div>
        <div class="container col-md-5 col-sm-12">
            <canvas id="skill_compare_chart" width="400" height="400"></canvas>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
    <script type="text/javascript" src="{% static 'pcrd_unpack/scripts/palette.js' %}"></script>

    <script>
        function hexToRgbA(hex){
            var c;
            if(/^#([A-Fa-f0-9]){6,8}$/.test(hex)){
                c= hex.substring(1).split('');
                if(c.length=== 3){
                    c= [c[0], c[0], c[1], c[1], c[2], c[2]];
                }
                c= '0x'+c.join('');
                if (c.length === 10) {
                    return 'rgba('+[(c>>24)&255, (c>>16)&255, (c>>8)&255, (c&255)/255].join(',')+')';
                }
                return 'rgba('+[(c>>16)&255, (c>>8)&255, c&255].join(',')+',1)';
            }
            throw new Error('Bad Hex');
        }
        function get_color(offset, border=false){
            var len = 8;
            offset = offset % len;
            var result = "";
            return palette('mpn65', len).map(function(hex) {
                if (border){
                    result =  '#' + hex;
                } else {
                result =  '#' + hex + "30";
                }
                return hexToRgbA(result)
            })[offset]
        }
        $(document).ready(function() {
            $('#unit_summary_list').DataTable({
                "order": [[ 3, "asc" ]],
                scrollY:        500,
                scrollX:        true,
                {#scrollCollapse: true,#}
                paging:         false,
                fixedColumns: {
                    leftColumns: 2
                }
            });
        } );


        var ctx = document.getElementById("exp_chart").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: {{ chart_datas.team.labels }},
                datasets: [
                    {
                        label: "{{ chart_datas.team.title }}",
                        data: {{ chart_datas.team.data }},
                        backgroundColor: get_color(1),
                        borderColor: get_color(1, true),
                        borderWidth: 1
                    },
                    {
                        label: "{{ chart_datas.unit.title }}",
                        data: {{ chart_datas.unit.data }},
                        backgroundColor: get_color(2),
                        borderColor: get_color(2, true),
                        borderWidth: 1
                    },
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        },
                        scaleLabel:{
                            display: true,
                            labelString: 'experience'
                        }
                    }]
                }
            }
        });

        var exp_compare_chart_ctx = document.getElementById("exp_compare_chart").getContext('2d');
        var exp_compare_chart = new Chart(exp_compare_chart_ctx, {
            type: 'line',
            data: {
                labels: {{ chart_datas.compare.labels }},
                datasets: [
                    {
                        label: "{{ chart_datas.compare.title }}",
                        data: {{ chart_datas.compare.data }},
                        backgroundColor: get_color(3),
                        borderColor: get_color(3, true),
                        borderWidth: 1
                    },
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        },
                        scaleLabel:{
                            display: true,
                            labelString: 'ratio'
                        }
                    }]
                }
            }
        });

        var skill_compare_chart_ctx = document.getElementById("skill_compare_chart").getContext('2d');
        var skill_compare_chart = new Chart(skill_compare_chart_ctx, {
            type: 'line',
            data: {
                labels: {{ chart_datas.skill_compare.labels }},
                datasets: [
                    {
                        label: "{{ chart_datas.skill_compare.title|title }}",
                        data: {{ chart_datas.skill_compare.data }},
                        backgroundColor: get_color(4),
                        borderColor: get_color(4, true),
                        borderWidth: 1
                    },
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        },
                        scaleLabel:{
                            display: true,
                            labelString: 'ratio'
                        }
                    }]
                }
            }
        });

        {% with chart_tag="skill_mana" %}

            var {{ chart_tag }}_chart_ctx = document.getElementById("{{ chart_tag }}_chart").getContext('2d');
            var {{ chart_tag }}_chart = new Chart({{ chart_tag }}_chart_ctx, {
                type: 'line',
                data: {
                    labels: {{ chart_datas.skill_mana.labels }},
                    datasets: [
                        {
                            label: "{{ chart_datas.skill_mana.title|title }}",
                            data: {{ chart_datas.skill_mana.data }},
                            backgroundColor: get_color(5),
                            borderColor: get_color(5, true),
                            borderWidth: 1
                        },
                    ]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero:true
                            },
                            scaleLabel:{
                                display: true,
                                labelString: 'ratio'
                            }
                        }]
                    }
                }
            });
        {% endwith %}
    </script>
{% endblock %}